class Makenote < Formula
  include Language::Python::Virtualenv

  desc "Fast terminal note logging to GitHub"
  homepage "https://github.com/hunterfinch/make-note"
  url "https://github.com/hunterfinch/make-note/archive/refs/tags/v0.1.0.tar.gz"
  # PLACEHOLDER — compute real hash at release time:
  #   curl -sL "https://github.com/hunterfinch/make-note/archive/refs/tags/v0.1.0.tar.gz" \
  #     | shasum -a 256 | awk '{ print $1 }'
  sha256 "PLACEHOLDER_COMPUTE_BEFORE_PUBLISHING"
  license "MIT"

  depends_on "python@3.12"
  depends_on "gh"

  # Resource stanzas below are generated by:
  #   brew update-python-resources --print-only Formula/makenote.rb
  # Run that command after updating url/sha256 above to refresh these hashes.
  resource "click" do
    url "PLACEHOLDER"
    sha256 "PLACEHOLDER"
  end

  resource "questionary" do
    url "PLACEHOLDER"
    sha256 "PLACEHOLDER"
  end

  resource "prompt-toolkit" do
    url "PLACEHOLDER"
    sha256 "PLACEHOLDER"
  end

  resource "wcwidth" do
    url "PLACEHOLDER"
    sha256 "PLACEHOLDER"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    system bin/"mn", "--version"
  end
end
